<?php
/**
 * @file
 * required_field_display functionality
 */

/**
 * Implements hook_preprocess_table().
 */
function required_field_display_preprocess_table(array &$table) {
  if (isset($table['attributes']['id']) && $table['attributes']['id'] == 'field-overview') {
    $field_info = NULL;
    foreach ($table['rows'] as $row_id => $row) {
      list($type, $bundle, $field) = explode('.', $row_id);
      if (empty($field_info)) {
        $field_info = \Drupal::getContainer()->get('entity_field.manager')->getFieldDefinitions($type, $bundle);
      }

      if (isset($field_info[$field]) && $field_info[$field]->isRequired()) {
        $table['rows'][$row_id]['cells']['label']['attributes']->addClass('form-required');
      }
    }
  }
}
